# Generated by Django 3.1 on 2020-12-12 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yapılacak Listesi')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Başlık')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('last_date', models.DateTimeField(verbose_name='Tarih')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('durum', models.BooleanField(default=False, verbose_name='Yapıldı')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici', to=settings.AUTH_USER_MODEL)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.todolist')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
