# Generated by Django 3.1 on 2020-12-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['-last_date']},
        ),
    ]
